import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers/Providers";
import { Toaster } from "sonner";

// const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] }); //

export const metadata: Metadata = {
  title: "Lost and Found App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
}
